### ISSUE TITLE
Handle scraped locale if locale doesn't exist in strapi

### ISSUE THREAD

**Issue by moncapitaine** [progwise/george-ai#65]
We need to solve it, best would be to add a locale to strapi if it does not exist and to have a fallback if the locale cannot we added to strapi.

Steps to reproduce:
1. remove locale de in strapi admin
2. run scrape that detects a german (de) locale

=> error
but should work

2nd possible solution:

Scrape only pages that have a locale that exists in Strapi.

**Comment by moncapitaine** [comment]
[2023-09-01 09:30:27.473] http: POST /graphql (7 ms) 200
[2023-09-01 09:30:27.489] error: This locale doesn't exist
ApplicationError: This locale doesn't exist
    at assignValidLocale (/Users/michael/src/temp/george-ai/node_modules/@strapi/plugin-i18n/server/services/entity-service-decorator.js:73:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (/Users/michael/src/temp/george-ai/node_modules/@strapi/plugin-i18n/server/services/entity-service-decorator.js:128:5)
    at async resolve (/Users/michael/src/temp/george-ai/node_modules/@strapi/plugin-graphql/server/services/builders/mutations/collection-type.js:52:23)
